---
- name: Update All packages
  become: yes
  become_user: root
  dnf: >
    name=* state=latest
  when: ansible_os_family == "RedHat"

- name: Install common packages
  become: yes
  become_user: root
  dnf: >
    name={{ item }} state=latest
  when: ansible_os_family == "RedHat"
  with_items:
    - "git"
    - "gcc"
    - "make"
    - "automake"
    - "gcc-c++"
    - "kernel-devel"
    - "python-virtualenv"
    - "python-devel"
    - "htop"
    - "nload"
    - "mlocate"
    - "policycoreutils-python"
    - "tmux"
    - "net-tools"
    - "emacs-nox"
    - "httpd-tools"
    - "wget"
    - "curl"
    - "bind-utils"
    - "nc"
    - "docker"
    - "golang"
    - "python3-devel"
    - "python-virtualenv"
    - "python3-virtualenv"
    - "ruby"
    - "vagrant"
    - "libvirt"
    - "guake"
#    - "atom"
    - "git"
    - "ethtool"
    - "vagrant-libvirt"
    - "rpmfusion-free-release"
    - "nautilus-open-terminal"
    - "gnome-tweak-tool"
    - "nodejs"
    - "npm"

- stat: path=/usr/bin/term
  register: term

- name: create a shortcut for the gnome-terminall called term
  command: sudo ln -s /usr/bin/gnome-terminal /usr/bin/term
  when: not term.stat.exists

- name: Remove current setup
  command: /usr/bin/rm -rf /home/{{ user_name }}/.emacs.d 

- name: Fetch emacs setup repo
  git: repo=https://github.com/PI-Victor/.emacs.d.git dest=/home/{{ user_name }}/.emacs.d clone=yes
  
- name: copy the .emacs to ~
  command: cp -p /home/{{ user_name }}/.emacs.d/.emacs /home/{{ user_name }}/

- name: Fetch tmux setup repo
  git: repo=https://github.com/PI-Victor/.tmux_conf.git dest=/home/{{ user_name }}/.tmux_conf clone=yes

- name: copy the .tmux.conf to ~
  command: cp -p /home/{{ user_name }}/.tmux_conf/.tmux.conf /home/{{ user_name }}/

- name: Ensure docker is added to systemctl
  become: yes
  become_user: root
  service: name=docker enabled=yes state=started

- name: Install bower globally
  become: yes
  become_user: root
  command: /usr/bin/npm install -g bower --allow-root
